find_package(OpenXR CONFIG REQUIRED)
find_package(glfw3 CONFIG REQUIRED)
find_package(OpenGL REQUIRED)
find_package(X11 REQUIRED)
add_executable(AROSXRDisplayBridge src/main.cpp)
target_compile_features(AROSXRDisplayBridge PRIVATE cxx_std_23)
target_link_libraries(AROSXRDisplayBridge PRIVATE AROSVirtualDisplay OpenXR::openxr_loader glfw OpenGL::GL X11::X11)
set_target_properties(AROSXRDisplayBridge PROPERTIES OUTPUT_NAME ar-os-xr-display)
install(TARGETS AROSXRDisplayBridge RUNTIME DESTINATION ${CMAKE_INSTALL_BINDIR})
