find_package(OpenXR CONFIG REQUIRED)
find_package(glfw3 CONFIG REQUIRED)
find_package(OpenGL REQUIRED)
find_package(X11 REQUIRED)
add_executable(VISROSXRDisplayBridge src/main.cpp)
target_compile_features(VISROSXRDisplayBridge PRIVATE cxx_std_23)
target_link_libraries(VISROSXRDisplayBridge PRIVATE VISROSVirtualDisplay OpenXR::openxr_loader glfw OpenGL::GL X11::X11)
set_target_properties(VISROSXRDisplayBridge PROPERTIES OUTPUT_NAME visr-os-xr-display)
install(TARGETS VISROSXRDisplayBridge RUNTIME DESTINATION ${CMAKE_INSTALL_BINDIR})
